/* eslint-disable translate-obj-prop/translate-obj-prop */
import { __ } from '../../../../admin/src/common/helpers/i18nWrap'

export default {
  chatLink: 'https://tawk.to/chat/60eac4b6d6e7610a49aab375/1faah0r3e',
  facebookCommunity: 'https://www.facebook.com/groups/bitcommunityusers',
  linkedIn: 'https://www.linkedin.com/company/bitapps',
  plugins: {
    // Mirrors the entry proposed upstream in _bitapps-plugin-commons (PR #21).
    // Held here until that merges — this directory is regenerated by
    // `pnpm plugin:commons:cp`, so once the PR lands this copy is simply
    // replaced by the identical upstream one rather than conflicting.
    'bit-connect': {
      buyLink: 'https://bitapps.pro/bit-connect/#pricing/',
      description: __(
        'A community forum for WordPress where users raise feature requests, report issues, send feedback and vote on what gets built next.'
      ),
      docLink: 'https://bitapps.pro/docs/bit-connect/',
      reviewLink: 'https://wordpress.org/support/plugin/bit-connect/reviews/',
      title: 'Bit Connect',
      website: 'https://bitapps.pro/bit-connect/',
      wpSupportThread: 'https://wordpress.org/support/plugin/bit-connect/'
    },
    'bit-crm-sales-marketing-automation': {
      buyLink: 'https://bit-crm.com/pricing/',
      description: __(
        'WordPress CRM to manage contacts, leads, deals, and invoices and run your whole sales pipeline right from your WordPress dashboard.'
      ),
      docLink: 'https://bitapps.pro/docs/bit-crm/',
      reviewLink: 'https://wordpress.org/support/plugin/bit-crm-sales-marketing-automation/reviews/',
      title: 'Bit CRM',
      website: 'https://bit-crm.com/',
      wpSupportThread: 'https://wordpress.org/support/plugin/bit-crm-sales-marketing-automation/'
    },
    'bit-pi': {
      buyLink: 'https://bit-flows.com/#pricing/',
      description: 'Bit Flows - ' + __('Zapier Alternative in WordPress Unlimited Task.'),
      docLink: 'https://bit-flows.com/users-guide/',
      reviewLink: 'https://wordpress.org/support/plugin/bit-pi/reviews/',
      title: 'Bit Flows',
      website: 'https://bit-flows.com',
      wpSupportThread: 'https://wordpress.org/support/plugin/bit-pi/'
    },
    'bit-social': {
      buyLink: 'https://bit-social.com/#pricing/',
      description: __(
        'An social media management plugin for WordPress, that allows you to share your post to different social media platform, schedule post, manage social media account and many more feature.'
      ),
      docLink: 'https://bit-social.com/documentation/',
      reviewLink: 'https://wordpress.org/support/plugin/bit-social/reviews/',
      title: 'Bit Social',
      website: 'https://bit-social.com',
      wpSupportThread: 'https://wordpress.org/support/plugin/bit-social/'
    }
  },
  supportEmail: 'support@bitapps.pro',
  x: 'https://x.com/bit_apps',
  youtubeChannel: 'https://www.youtube.com/@bit-apps'
} as const
