import { __ } from '@common/helpers/i18nWrap'
import { Alert, Descriptions, Tag, Typography } from 'antd'

import { SEO_PLUGIN_LABELS, type SeoDiagnostics } from '../shared/types'

const { Title } = Typography

/**
 * What is actually live, as opposed to what has been asked for.
 *
 * Every value here is read from the running site, not from the form — an
 * administrator otherwise has no way to tell whether their SEO plugin is
 * winning, whether crawlers can see the portal at all, or how much of the
 * community is indexable.
 */
export default function SeoStatus({ diagnostics }: { diagnostics: SeoDiagnostics }) {
  const pluginLabel = diagnostics.seoPlugin
    ? (SEO_PLUGIN_LABELS[diagnostics.seoPlugin] ?? diagnostics.seoPlugin)
    : __('None detected')

  const indexableArchives = Object.entries(diagnostics.archives).filter(
    ([, archive]) => archive.indexable
  )
  const archiveUrlCount = indexableArchives.reduce((total, [, archive]) => total + archive.terms, 0)

  return (
    <div className="bc-mb-6 bc-rounded-lg bc-border bc-border-solid bc-border-line bc-bg-surface bc-p-6">
      <Title className="bc-mb-4" level={4}>
        {__('Current status')}
      </Title>

      {!diagnostics.portalIsPublic && (
        <Alert
          className="bc-mb-4"
          description={__(
            'The portal is restricted to logged-in members, so nothing is exposed to search engines. These settings take effect once the portal is public.'
          )}
          message={__('Portal is members-only')}
          showIcon
          type="warning"
        />
      )}

      {diagnostics.portalIsPublic && !diagnostics.crawlerContent && (
        <Alert
          className="bc-mb-4"
          description={__(
            'Search engines and AI crawlers cannot read the portal, because the content they receive is generated by the setting below.'
          )}
          message={__('Content for crawlers is switched off')}
          showIcon
          type="warning"
        />
      )}

      <Descriptions bordered column={1} size="small">
        <Descriptions.Item label={__('SEO plugin detected')}>
          <span className="bc-font-medium">{pluginLabel}</span>
          {diagnostics.seoPlugin && (
            <Tag className="bc-ml-2" color={diagnostics.isBridged ? 'blue' : 'default'}>
              {diagnostics.isBridged
                ? __('It prints the portal tags, using our data')
                : __('Bit Connect prints the portal tags')}
            </Tag>
          )}
        </Descriptions.Item>

        <Descriptions.Item label={__('Portal URL')}>
          <a href={diagnostics.portalUrl} rel="noreferrer" target="_blank">
            {diagnostics.portalUrl || '—'}
          </a>
        </Descriptions.Item>

        <Descriptions.Item label={__('Sitemap')}>
          {diagnostics.sitemapUrl ? (
            <a href={diagnostics.sitemapUrl} rel="noreferrer" target="_blank">
              {diagnostics.sitemapUrl}
            </a>
          ) : (
            '—'
          )}
        </Descriptions.Item>

        <Descriptions.Item label={__('Published topics')}>
          <span className="bc-font-medium">{diagnostics.publishedTopics}</span>
        </Descriptions.Item>

        <Descriptions.Item label={__('Indexable archive pages')}>
          <span className="bc-font-medium">{archiveUrlCount}</span>
          <span className="bc-ml-2 bc-text-xs bc-text-ink-subtle">
            {indexableArchives.length > 0
              ? `(${indexableArchives.map(([segment]) => `/${segment}`).join(', ')})`
              : __('(no archives are indexable)')}
          </span>
        </Descriptions.Item>
      </Descriptions>
    </div>
  )
}
